[package]
name = "ozy_engine"
version = "0.1.0"
authors = ["Nick Driscoll <nick.a.mavros@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = "0.39.1"
gl = "0.10.0"
image = "*"
nalgebra-glm = "0.5"